name: Upload Codex

on:
  # push:
  #   branches:
  #     # - main 
      
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  upload-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: 'data'
          path: './data'
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install scrapy
      - name: Start crawler for codex
        run: |
          python script.py codex --dir tmp --target '${{ vars.TARGET }}'
      - name: Gen crawler timestamp
        run: |
          echo $(date -u +%s) > ./tmp/finished
      - name: Gen Url List
        run: |
          python script.py urllist -o ./data/urllist.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: codex-data
          path: ./tmp
      - name: Push changes
        shell: bash
        run: |
          cd data
          git add .
          if [ ! -z "$(git --no-pager diff --staged)" ]; then
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -s -m "Data Update $(date +%Y%m%d%H%M)" -a
            git push
          fi